---
abstract: 'A module to implement some of AutoConf macros in pure perl.'
author:
  - 'Alberto Simoes <ambs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-AutoConf
no_index:
  directory:
    - t
    - inc
requires:
  Capture::Tiny: 0
  ExtUtils::CBuilder: 0.23
  Test::More: 0
version: 0.18
