--- #YAML:1.0
name:               Config-AutoConf
version:            0.12_2
abstract:           A module to implement some of AutoConf macros in pure perl.
author:
    - Alberto Simoes <ambs@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::CBuilder:  0.23
    Test::More:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
